services:
  - type: web
    name: smart-travel-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
